"""Generate or check the complete non-secret environment reference."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
from statement_ledger.infrastructure.settings import (  # noqa: E402
    ENV_FIELDS,
    SECRET_ALIASES,
    Settings,
)


def render() -> str:
    lines = [
        "# Generated by scripts/generate-environment.py; never put real credentials here.",
        "# .env is loaded explicitly by Compose or --env-file, never implicitly by the library.",
        "# Defaults < selected TOML < explicit dotenv < process environment < non-secret CLI.",
    ]
    settings = Settings()
    for name, field in ENV_FIELDS.items():
        value = getattr(settings, field)
        if value is None:
            example = (
                "data/jobs.sqlite3" if field == "legacy_jobs_path" else "data/db/ledger.sqlite3"
            )
            lines.append(f"# {name}={example}")
        else:
            value = int(value) if isinstance(value, bool) else value
            lines.append(f"{name}={value}")
    lines += [
        "",
        "# Control inputs (optional):",
        "# SL_CONFIG_FILE=config/local.toml",
        "# SL_ENV_FILE=.env",
        "# SL_SECRET_DIR=/run/secrets",
        "# Live-test opt-in: local agent only; leave unset in CI.",
        "SL_RUN_LIVE=",
        "",
        "# Empty credentials are valid while their operation is disabled.",
    ]
    for name, aliases in SECRET_ALIASES.items():
        lines.append(f"SL_SECRET_{name}=")
        lines.append("# Transitional aliases (conflicting values fail): " + ", ".join(aliases))
    return "\n".join(lines) + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    path = ROOT / ".env.example"
    text = render()
    if args.check:
        if not path.exists() or path.read_text(encoding="utf-8") != text:
            raise SystemExit(".env.example is out of date; regenerate it")
    else:
        path.write_text(text, encoding="utf-8")
